WebApplication1/Models/Tweet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Tweet
    {
        public string Name { get; set; }
        public string Text { get; set; }
        public DateTime Created { get; set; }
        public double Sentiment { get; set; }
    }
}

WebApplication1/Models/TweetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class TweetViewModel
    {
        public string AllData { get; set; }
        public List<Tweet> TweetData { get; set; }

        public double AverageSentiment { get; set; }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Controllers/TweetController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using WebApplication1.Models;
using System.Configuration;
using System.Linq;


namespace WebApplication1.Controllers
{
    public class TweetController : Controller
    {
        public async Task<ActionResult> Index(string data)
        {
            var model = new TweetViewModel();

            if (data.IsNullOrWhiteSpace())
            {
                model.AllData = "Like: http://localhost:49901/Tweet/?data=onepunchman";
                model.TweetData = FinalStore.GetTweets();

                var jj = new SentimentAnalysis();
            }
            else
            {
                TwitterAdapter.ConsumerKey = ConfigurationManager.AppSettings["TwitterConsumerKey"];
                TwitterAdapter.ConsumerSecret = ConfigurationManager.AppSettings["TwitterConsumerSecret"];
                var results = await TwitterAdapter.SearchAsync(data);

                model.AllData = results;
            }

            return View(model);
        }

        public async Task<ActionResult> ShowGraph()
        {
            var allTweets = FinalStore.GetTweets();
            var model = new TweetViewModel();

            model.TweetData = allTweets;
            model.AverageSentiment = allTweets.Count > 0 ? allTweets.Average(x => x.Sentiment) : -1;
            return View(model);
        }

        public ActionResult AddTweet(Tweet tweet)
        {
            FinalStore.AddTweet(tweet);
            return RedirectToAction("Index");
        }

        public ActionResult Reset()
        {
            FinalStore.Reset();
            return RedirectToAction("Index");
        }
    }

}

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

        @RenderBody()


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Tweet/Index.cshtml
@model WebApplication1.Models.TweetViewModel
    




@if (Model.TweetData != null)
{
    foreach (var tweet in Model.TweetData)
    {

        <div class="EmbeddedTweet-tweet">
            <blockquote class="Tweet h-entry js-tweetIdInfo subject expanded" >
                <div class="Tweet-header">
                    <div class="Tweet-brand">
                        <a data-scribe="element:logo">
                            <span class="FollowButton-bird">
                                <div class="Icon Icon--twitter " aria-label="View on Twitter" title="View on Twitter" role="presentation"></div>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="Tweet-body e-entry-content" data-scribe="component:tweet">
                    <div class="u-hiddenVisually js-inViewportScribingTarget"></div>
                    <p class="Tweet-text e-entry-title" lang="en" dir="ltr">
                        @tweet.Text
                    </p>
                    <div class="Tweet-metadata dateline">
                        <a class="u-linkBlend u-url customisable-highlight long-permalink" data-datetime="2014-05-05T22:09:42+0000" data-scribe="element:full_timestamp">
                            <time class="dt-updated" >@tweet.Created.ToLongTimeString() @@@tweet.Name</time>
                        </a>
                    </div>
                </div>
            </blockquote>
        </div>

    }






    using (@Html.BeginForm("AddTweet", "Tweet", FormMethod.Post))
    {

        <div class="form-group">
            <label for="exampleInputEmail1">Name</label>
            <input name="tweet.Name" value="" maxlength="100" class="form-control" id="exampleInputEmail1">
           
        </div>
        <div class="form-group">
            <label for="exampleTextarea">Message</label>
            <textarea class="form-control" id="exampleTextarea" rows="3" name="tweet.Text" value="" maxlength="255" required></textarea>

        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    }

}
else
{

    Layout = null;

    @Model.AllData

}

WebApplication1/Views/Tweet/ShowGraph.cshtml
@model WebApplication1.Models.TweetViewModel

@{
    ViewBag.Title = "Show Graph";
}

<h2>Sentiment</h2>

Average Sentiment: @Model.AverageSentiment

@if(Model.TweetData != null && Model.TweetData.Count >= 2)
{
    for (var i = Model.TweetData.Count-1; i > Model.TweetData.Count - 3; i--)
    {
        // only show last 2 tweets
        var tweet = Model.TweetData[i];

        <div class="EmbeddedTweet-tweet">
            <blockquote class="Tweet h-entry js-tweetIdInfo subject expanded">
                <div class="Tweet-header">
                    <div class="Tweet-brand">
                        <a data-scribe="element:logo">
                            <span class="FollowButton-bird">
                                <div class="Icon Icon--twitter " aria-label="View on Twitter" title="View on Twitter" role="presentation"></div>
                            </span>
                        </a>
                    </div>
                </div>
                <div class="Tweet-body e-entry-content" data-scribe="component:tweet">
                    <div class="u-hiddenVisually js-inViewportScribingTarget"></div>
                    <p class="Tweet-text e-entry-title" lang="en" dir="ltr">
                        @tweet.Text
                    </p>
                    <div class="Tweet-metadata dateline">
                        <a class="u-linkBlend u-url customisable-highlight long-permalink" data-datetime="2014-05-05T22:09:42+0000" data-scribe="element:full_timestamp">
                            <time class="dt-updated">@tweet.Created.ToLongTimeString() @@@tweet.Name</time>
                        </a>
                    </div>
                </div>
            </blockquote>
        </div>
    }
}